In [24]:
import pandas as pd
df = pd.read_csv("clean4_car_price.csv")
df1 = df
df1.columns

Index(['Unnamed: 0', 'car_name', 'car_prices_in_rupee', 'kms_driven',
       'fuel_type', 'transmission', 'ownership', 'manufacture', 'engine',
       'Seats', 'zscore'],
      dtype='object')

In [36]:
#define x and y
# df1['car_prices_in_rupee'] = pd.cut(df1['car_prices_in_rupee'], bins=10, labels=False)
x = df1[['engine', 'manufacture','Seats','kms_driven','ownership','fuel_type','transmission']]

y = df1['car_prices_in_rupee']

In [37]:
#import classification algos and cross validation 
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [38]:
#Cross validation for SVC 
cross_val_score(SVC(),x, y, cv = 5)

c:\Users\student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


array([0.87305936, 0.8738574 , 0.8738574 , 0.87294333, 0.87294333])

In [39]:
#Cross validation for Decision Tree 
cross_val_score(DecisionTreeClassifier(), x, y, cv = 5)

c:\Users\student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


array([0.86575342, 0.83912249, 0.89396709, 0.89031079, 0.90767824])

In [40]:
#Cross validation for Logistic regression 
cross_val_score(LogisticRegression(), x, y, cv = 5)

c:\Users\student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\student\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\student\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.

array([0.87305936, 0.86928702, 0.87202925, 0.87202925, 0.87294333])

In [41]:
#Cross validation for Random forest 
cross_val_score(RandomForestClassifier(n_estimators=50), x, y, cv = 5)

c:\Users\student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


array([0.88858447, 0.88025594, 0.90767824, 0.89396709, 0.90859232])

In [42]:
#Cross validation for KNN 
cross_val_score(KNeighborsClassifier(),x, y ,cv = 5)

c:\Users\student\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\student\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
c:\Users\student\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, th

array([0.85936073, 0.85648995, 0.86928702, 0.84917733, 0.86106033])

In [43]:
#Train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [44]:
#Model design
model = RandomForestClassifier() 
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [45]:
#Confusion matrix
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred)
cm

array([[929,  12,   8,   5,   0,   0,   0,   0,   0,   0],
       [ 31,  24,   5,   3,   0,   0,   0,   0,   0,   1],
       [ 16,   8,  19,   2,   0,   0,   0,   0,   0,   0],
       [  2,   4,   2,   8,   1,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  2,   1,   0,   0,   0,   1,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  3,   0,   0,   0,   0,   0,   0,   0,   0,   1]], dtype=int64)

In [46]:
#Accuracy
print(accuracy_score(y_test, model.predict(X_test)))

0.8968036529680365


In [48]:
# Importing necessary libraries
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error

# Generating some sample data
# X, y = make_regression(n_samples=1000, n_features=10, noise=0.1, random_state=42)
x = df1[['engine', 'manufacture','Seats','kms_driven','ownership','fuel_type','transmission']]

y = df1['car_prices_in_rupee']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Creating a Random Forest Regressor model
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Training the model
rf_regressor.fit(X_train, y_train)

# Making predictions on the test set
y_pred = rf_regressor.predict(X_test)

# Evaluating the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)


Mean Squared Error: 0.4412548102739726


In [49]:
from sklearn.metrics import r2_score

# Calculating R^2 score
r2 = r2_score(y_test, y_pred)
print("R^2 Score:", r2)


R^2 Score: 0.528967857858748


In [53]:
# Importing necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Loading the Iris dataset

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=40)

# Creating a Random Forest Classifier model
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=40)

# Training the model
rf_classifier.fit(X_train, y_train)

# Making predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.9059360730593607
